const biografia = document.getElementById('biografia');

const harryPotter = document.getElementById('harry-potter');

const citar = document.getElementById('citar');

const texto = `
    <p>La escritora británica Joanne Kathleen Rowling se hizo célebre con su serie de novelas dedicadas a las aventuras de Harry Potter, uno de los mayores fenómenos literarios de la historia. Las peripecias de un niño huérfano con poderes mágicos capaz de evadirse a voluntad a un mundo de fantasía consiguieron batir todos los récords de ventas en la literatura del género, aunque muchos críticos se mostraron reacios a encasillar los libros de Rowling como cuentos para niños, como ocurriera con el famoso Tom Sawyer de Mark Twain. </p>
    <figure>
        <img src="https://www.biografiasyvidas.com/reportaje/rowling/fotos/rowling340.jpg" alt="la autora" width="250px">
        <figcaption>J. K. Rowling</figcaption>
    </figure> 
    <p>La persona que hizo posible que muchos niños y adolescentes prefiriesen leer un libro a pasar las horas muertas delante del televisor es una tímida británica que se propuso escribir siete entregas de la serie, que equivalen a los cursos que el protagonista debe superar en la escuela de magia y hechicería a la que asiste cuando se escapa de la horrible realidad cotidiana en casa de sus mezquinos tíos. <br>Según algunos críticos literarios, la autora logró crear en sus novelas una inquietante atmósfera atractiva a los ojos de lectores de muy diversa condición y edad, a partir de influencias reconocibles en los libros de escritores británicos como Enid Blyton, Richmal Crompton o Roald Dahl. Pero, paradójicamente, ella misma afirmaba que nunca pretendió escribir fantasía y que la idea le surgió a partir de sus propios recuerdos de la infancia. Prácticamente desconocida y con problemas económicos en la primera mitad de la década de los noventa, cuando vivía de una modesta pensión como desempleada, J. K. Rowling se convirtió en una mujer rica y popular en Europa y sobre todo en Estados Unidos, donde multitudes de niños acompañados por sus padres soportarían largas colas en las librerías para hacerse con las últimas aventuras del pequeño mago.</p>
    <h2>La infancia que nutrió a Potter</h2>
    <p>Joanne Kathleen Rowling nació el 31 de julio de 1965 en la pequeña localidad británica de Chipping Sodbury, cerca de Bristol, en el suroeste de la isla. Debido al trabajo de su padre, Peter, ingeniero de la compañía Rolls-Royce casado con Anne, una escocesa con raíces francesas, su familia tuvo que cambiar de residencia en varias ocasiones durante la infancia de las pequeñas Jo y Di, cariñosos apelativos familiares de la futura novelista y su hermana menor, Dianne. <br>Tras una breve estancia en Yate, se mudaron a Winterbourne, siempre sin alejarse de los suburbios de Bristol, entorno en el que se forjaron los primeros recuerdos de la imaginativa niña, que pasaba horas compartiendo sueños y fantasías con su hermana. Lectora y escritora precoz, entusiasta aficionada a devorar novelas para adultos, a los seis años ideó un conejo que tuvo el honor de ser su primer héroe en un cuento que tituló Rabbit. </p> 
    <figure>
        <img src="https://www.biografiasyvidas.com/reportaje/rowling/fotos/daniel_radcliffe.jpg" alt="escena de pelicula de harry-potter" width="250px">
        <figcaption>Daniel Radcliffe interpretó el papel de Harry Potter
        en todas las películas, creciendo con el personaje</figcaption>
    </figure> 
    <p>En Winterbourne las niñas hicieron amigos entre el vecindario; uno de ellos se llamaba Ian Potter. Aficionada a adoptar nombres extraños para los protagonistas y lugares de sus novelas, muchos años después Joanne tomó prestado ese apellido para dar vida a su famoso personaje. Cuando Jo tenía nueve años, los Rowling hicieron realidad su sueño y se mudaron a un área rural del condado de Gwent llamada Forest of Dean, núcleo de población cercano a Chepstow, donde las dos hermanas descubrieron el placer de jugar en los verdes campos británicos próximos al río Wye. <br> Pero el feliz cambio tuvo su contrapartida en los problemas en la nueva escuela a la que asistieron las Rowling y que acabó por convertirse en un tormento para la mayor de las hermanas, quien recordaría durante años a su odiada profesora Mrs. Morgan, hasta el punto de trasladarla a sus novelas y hacer que encarnara a uno de sus malévolos personajes. <br>La pecosa, estudiosa y bastante insegura «gafotas» Joanne, según su propia definición, creció y dejó la escuela primaria de Tutshill para entrar en la de Wyedean, donde empezó a interesarse por los idiomas. Alumna aplicada, pronto destacó también por su afición a contar historias a un reducido círculo de amigos, quienes escuchaban con atención la narración de largos relatos en los tiempos del recreo. Durante su adolescencia escribió mucho, pero, con la excepción de algunos divertidos cuentos, nunca se atrevió a mostrar sus manuscritos a nadie.</p>
    <h2>Años difíciles</h2>
    <p>Una vez graduada en Wyedean, Joanne K. Rowling se matriculó en la Universidad de Exeter, donde, siguiendo el consejo paterno, estudió francés con el propósito de encontrar después un buen trabajo como secretaria bilingüe. Con los títulos de lengua y literatura francesas todavía relucientes, se trasladó a la sede de Amnistía Internacional en Londres para realizar un trabajo de investigación sobre las violaciones a los derechos humanos en el África francófona. </p>
    <figure>
        <img src="https://www.biografiasyvidas.com/reportaje/rowling/fotos/piedra_filosofal.jpg" alt="escena de pelicula de harry-potter" width="250px">
    <figcaption>Harry Potter y la piedra filosofal, primera entrega
    de la serie, fue llevada al cine en 2001</figcaption>
    </figure> 
    <p> Tras este breve período de formación empezó a trabajar como secretaria, pero pronto descubrió que el orden y la rutina no iban con ella. Varias experiencias frustrantes en diferentes empresas, unidas a la triste desaparición de su madre, enferma de esclerosis múltiple, la llevaron a dejarlo todo a los veintiséis años y a abandonar el país con la intención de enseñar inglés en el extranjero. <br> En Lisboa disfrutó enseñando su lengua materna a alumnos portugueses y tuvo bastante tiempo para escribir, su verdadera vocación. Allí conoció y se enamoró de Jorge Arantes, un periodista de la televisión portuguesa con el que contrajo matrimonio en octubre de 1992 y con quien, un año más tarde, tuvo una hija a la que llamó Jessica «en honor a una brigadista británica que había luchado en la guerra civil española», según afirmó en una entrevista. Pese al feliz acontecimiento, el matrimonio no prosperó y pronto acabó en divorcio. <br> Madre de una niña pequeña y sola en un país extranjero, en 1996 Joanne decidió regresar a Gran Bretaña y se instaló en la ciudad escocesa de Edimburgo, cerca de su hermana Dianne, donde llegó con la firme intención de acabar y publicar una novela sobre un tal Harry Potter, personaje infantil con poderes mágicos, cuyas andanzas había imaginado bastante tiempo atrás durante un interminable viaje en tren entre Manchester y Londres. <br> La tenaz profesora de francés pasó muchas tardes de su vida escribiendo «para sí misma» en un cálido café próximo a un pequeño apartamento sin calefacción en el que malvivía con su hija. Finalmente, la infatigable novelista logró una beca del Scottish Arts Council que le permitió concluir, cinco años después de empezada, la que entonces era la obra de su vida: Harry Potter y la piedra filosofal.</p>
    <h2>El éxito</h2>
    <p>Recorrió sin éxito con la copia mecanografiada por ella misma editoriales del prestigio de Penguin y Harper Collins, hasta que en 1997 consiguió por fin que la prestigiosa firma británica Bloomsbury publicara el libro. Pocos meses después, Scholastic Press compró los derechos de la novela para Estados Unidos, por una suma superior a los 14,5 millones de pesetas, una cifra muy importante para un libro infantil. Rowling empezó a ser popular en su propio país, y durante los primeros meses se vio ampliamente superada por la situación, sin poder escribir ni una sola línea. <br> A punto de acabar el segundo libro de la serie, entró en una fase crítica y llegó a pensar que estaba escribiendo «basura», según confesaría tiempo después en una entrevista. Nada acostumbrada a manejar semejantes sumas de dinero ni a la presión de los medios de comunicación, Joanne se bloqueó y tardó en adaptarse a la nueva situación, hasta el punto de verse obligada a modificar su sencillo estilo de vida. Tuvo que dejar de escribir en el mismo café debido al acoso de admiradores y curiosos, que convirtieron el local en lugar de peregrinación, y adoptó una postura defensiva frente a las intromisiones en su vida privada. Después decidió dejar las clases definitivamente para dedicarse por entero a lo que siempre había anhelado: escribir. </p>
    <figure>
     <img src="https://www.biografiasyvidas.com/reportaje/rowling/fotos/rowling_murray.jpg" alt="con su marido" width="250px">
     <figcaption>Con Neil Murray, su segundo marido</figcaption>
    </figure> 
    <p> La publicación de su primer libro -firmado con las iniciales J. K. por consejo de los editores, recelosos de que los niños no quisieran leer un libro sobre un chico escrito por una mujer- supuso un giro mágico en su vida. La realidad del extraordinario éxito superó ampliamente todas las expectativas de las editoriales británica y estadounidense que lo habían publicado. Las posteriores ediciones de los siguientes libros de la serie (Harry Potter y la cámara secreta y El prisionero de Azkabán) reafirmaron el éxito inicial y dieron lugar a un fenómeno literario, al que la prensa denominó «pottermanía». <br>Condecorada con el título de Oficial del Imperio Británico y convertida en la persona que ocupa el tercer lugar por volumen de ganancias en su país, según un listado de la prestigiosa revista Forbes, Joanne trató de mantener contra viento y marea su discreto estilo de vida. Todas las mañanas siguió llevando a su hija al colegio siempre que las giras promocionales de sus novelas se lo permitían, y procuró escribir los restantes libros de Harry Potter en otros cafés de Edimburgo, lejos del acoso de los periodistas.</p>
`
biografia.innerHTML = texto;

const texto2 = `
            <p>Rowling imaginó por primera vez a Harry Potter en 1990 y estructuró las peripecias de su héroe en siete posibles libros, cada uno de los cuales comprendería un año de la vida adolescente del aprendiz de brujo. Como es tradicional en la literatura clásica inglesa, su personaje tendría que enfrentarse a un medio familiar adverso (en este caso a sus odiados tíos) y a las fuerzas del Mal, y sería la magia el camino para vencer las fuerzas oscuras. </p>
            <figure>
                <img src="https://www.biografiasyvidas.com/reportaje/rowling/fotos/rowling340d.jpg" alt="J. K. Rowling" width="250px">
                <figcaption class="figcaptions-normales">J. K. Rowling</figcaption>
            </figure> 
            <p>Las tramas de la serie Potter son avatares y sorpresas fantásticas que suceden en la vida cotidiana, equilibrio que agrada a sus lectores. Harry Potter, que representa el Bien, recibe la confirmación de que posee poderes mágicos y que debe emplearlos para acabar con un personaje que representa el Mal, Voldemort. <br> En los libros de Rowling también sobresale la invención de personajes memorables como Ron Weasley, un mago experto de familia pobre; Albus Dumbledore, el director del colegio Hogwarts y el mago vivo más poderoso; Flitwick, diminuto y viejo brujo; Hooch, la profesora de vuelo; Severus Snape, aficionado a la magia negra y jefe de la casa Slytherin, de donde proceden magos tan terribles como Voldemort; los gnomos banqueros, peligrosos seres que custodian los tesoros guardados en Gringotts, a cientos de kilómetros bajo el centro de Londres; Argus Filch, celador del colegio y al que los estudiantes odian, y un largo etcétera. <br> Otra de las peculiaridades de sus libros es crear una topología pintoresca y memorable con lugares como El Bosque Prohibido, sitio vedado para los estudiantes de Hogwarts, pues allí viven criaturas mágicas; Gringotts, el banco de los magos; Hogsmeade, pueblo enteramente mágico; el Ministerio de Magia; y Andén 9 y 3/4, de donde sale el Hogwarts Express. <br> Los padres de Harry Potter, también magos, murieron en un enfrentamiento fatal contra Voldemort, el poderoso y oscuro hechicero. Al quedar huérfano, Harry fue recogido en casa de sus tíos, una mediocre familia de clase media que lo maltrata. Al cumplir los once años, se revela su pertenencia al mundo de los magos y es llevado a Hogwarts, una escuela-internado inusual en un mundo paralelo al ordinario donde encontrará verdaderos amigos y maestros, pero donde también tendrá que enfrentarse a temibles y poderosos enemigos. <br> En la primera entrega de la serie, Harry Potter y la piedra filosofal, Harry Potter, recién ingresado en el internado de Hogwarts, entabla amistad con Ron Weasley y Hermione Granger. El centro es parte de la casa Gryffindor, en la que, según asegura la leyenda, sólo moran los valientes. Pero no todos los personajes que le rodean son amigos, como queda patente tras la aparición de Draco Malfoy, quien se complace en hacer la vida imposible al pobre Harry. Pronto saldrá a escena también el poderoso mago Lord Voldemort, el brujo más perverso de todos los tiempos, que intenta acabar con la vida del protagonista después de haber dado muerte a sus padres. Pero Harry Potter advierte que su peligroso enemigo está ahora mucho más debilitado, por lo que no duda en enfrentarse abiertamente contra él.</p>
            <figure>
                <img src="https://www.biografiasyvidas.com/reportaje/rowling/fotos/camara_secreta_2.jpg" alt="Fotogramas de Harry Potter y la Cámara Secreta (2002)" width="250px">
                
                <figcaption id="figcaption-largo">Fotogramas de Harry Potter y la Cámara Secreta (2002)</figcaption>
                
                <img src="https://www.biografiasyvidas.com/reportaje/rowling/fotos/camara_secreta_1.jpg" alt="escena de pelicula de harry potter" width="250px"> 
                
            </figure>
            <p>En el segundo libro, Harry Potter y la Cámara Secreta, Ron Weasley y sus hermanos gemelos Fred y George acuden a Privet Drive, en donde Harry Potter está pasando las vacaciones, para rescatarlo de tan espantoso lugar y llevarlo hasta su casa. De regreso al internado de Hogwarts, Harry y Ron encuentran numerosas dificultades para llegar hasta el colegio, debido, entre otras causas, a que pierden el tren que debería conducirles hasta allí. <br> Cuando finalmente consiguen llegar al centro donde ambos están internos, se encuentran con que Hogwarts está amenazado por un monstruo terrible que ronda por los pasillos e intenta aniquilar a los alumnos de "sangre sucia", es decir, los pertenecientes a la estirpe de los muggles. El terror se ha generalizado incluso entre los profesores, que han decretado desesperadas medidas de seguridad para preservar la vida de los alumnos. Pero será Harry Potter quien se encargue de enfrentarse con el horrible monstruo y, de paso, descubrir los misterios de la inquietante Cámara Secreta.  <br> En la tercera parte, titulada Harry Potter y el prisionero de Azkaban, Sirius Black, un despiadado asesino dotado de poderes mágicos, acaba de huir de la prisión mágica de Azkaban, en la que había sido encerrado por haber matado a doce muggles y a un mago que había sido compañero suyo de colegio, al que aniquiló con un solo movimiento de varita mágica. <br> En el solemne Ministerio de la Magia, los magos que lo regentan se han tenido que servir de numerosos hechizos para que los muggles perdieran la memoria de lo ocurrido y acabaran aceptando que la muerte de los suyos fue debida a una accidental explosión de gas. Por Hogwarts corre el rumor de que Sirius Black se ha vuelto loco de remate y sólo quiere acabar con la vida de Harry Potter, por lo que el Ministerio de la Magia envía al internado a una delegación de vigilantes de Azkaban (los famosos dementores), con la misión de atrapar a Sirius. Pero los dementores causan un efecto muy negativo en la escuela, ya que sólo se alimentan de la alegría y la energía positiva de la gente, por lo que la tristeza y la angustia se apoderan de los habitantes de Hogwarts. <br> En Harry Potter y el cáliz de fuego, cuarta pieza de la serie, Ron está furioso y celoso porque su amiga Hermione, a la que ama en secreto, se ha enamorado de un chico nuevo, Victor Krum. Por su parte, el bueno de Harry Potter ha caído también bajo la tiranía del amor, y bebe los vientos por la joven Cho Chang, recién nombrada capitana del equipo de quidditch de Ravenclaw.</p>
            <figure>
                <img src="https://www.biografiasyvidas.com/reportaje/rowling/fotos/caliz_de_fuego_1.jpg" alt="Harry Potter y el cáliz de fuego (2005)" width="250px">
                <figcaption class="figcaptions-normales">Harry Potter y el cáliz de fuego (2005)</figcaption>
                <img src="https://www.biografiasyvidas.com/reportaje/rowling/fotos/caliz_de_fuego_2.jpg" alt="escena de pelicula de harry-potter">
            </figure>
            <p>Movido por esta pasión, consigue que Hermione, Ron y su hermano mayor Bill le acompañen a ver jugar al equipo de Cho Chang, que participa en los Mundiales de quidditch que se celebran aquel año. Todo transcurre en aparente calma hasta que, nada más acabar los Mundiales, aparece en el cielo un signo terrible que espanta a todos los que lo contemplan: la marca inconfundible de Lord Voldemort. <br> El quinto libro, Harry Potter y la Orden del Fénix, comienza tras unas aburridas vacaciones con sus tíos, durante las cuales Harry Potter no ha tenido ninguna noticia de sus amigos Ron y Hermione, Harry Potter va a iniciar su quinto año en el internado de Hogwarts, escuela de magia y hechicería en la que descubrió sus poderes. Pero en Privet Drive es atacado por los dementores, los vigilantes de la prisión de Azkaban, en la que estaba preso Sirius Black. <br> Harry Potter y el misterio del príncipe relata el sexto curso de Harry Potter en Hogwarts; Lord Voldemort se convierte en una amenaza aun más seria para toda la comunidad mágica y muggle. Harry descubre detalles del pasado del poderoso mago malvado y un Libro de Pociones que tal vez pueda ayudarle a combatir muchos de los terribles peligros que acechan la escuela; el autor de las anotaciones que figuran en el libro es el misterioso "príncipe". <br> El éxito de Harry Potter radica tanto en la maestría de Rowling para crear un personaje que colma las expectativas fantásticas y aventureras del lector infantil como en su capacidad para ofrecer al público adulto una historia mágica que recupera ese mundo añorado de la infancia, plagado de símbolos que, poco a poco, permitían ir asimilando el complejo universo de los mayores. <br> La calidad de los personajes recreados, los detalles de ese mundo prodigioso tan cercano al real pero mucho más estimulante, la intriga y resolución de las aventuras han hecho de Harry Potter un best-seller de la literatura mundial y suscitado el fenómeno de la "pottermanía". En 2004, las sucesivas entregas se habían traducido a más de cuarenta idiomas y se habían vendido más de cincuenta millones de ejemplares. Los dos primeros libros fueron llevados al cine por Chris Columbus y el tercero por el mejicano Alfonso Cuarón.</p>
         </div>   

`
harryPotter.innerHTML = texto2;

const texto3 = `
      <p id="p-de-citar">Cómo citar este artículo: Fernández, Tomás y Tamaro, Elena. «J.       K. Rowling. Biografía». En Biografías y       Vidas. La enciclopedia biográfica en       línea [Internet]. Barcelona, España,       2004. Disponible en <a href="https://      www.biografiasyvidas.com/reportaje/      rowling/harry_potter.htm">https://www.      biografiasyvidas.com/reportaje/rowling/      </a>.</p> 
`

citar.innerHTML = texto3;


